"""`docspine render`: generated regions and views (STANDARD.md sections 4 and 11).

`plan()` computes the complete new text of every file render manages. `run()` writes the
files that differ; `check` uses the same plan to report regions that are out of date.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, List, Optional

from .project import Artifact, Project
from .text import TEXTS, strip_code

STORY_ORDER = ("open", "in-progress", "verified", "superseded", "retired")
REQ_ORDER = ("proposed", "planned", "implemented", "rejected", "superseded")
ADR_ORDER = ("proposed", "accepted", "rejected", "superseded")
CHAPTERS = ("01-goals", "02-constraints", "03-context", "04-strategy", "05-building-blocks",
            "06-runtime", "07-deployment", "08-concepts", "09-decisions", "10-quality",
            "11-risks", "12-glossary")
GENERATED_HEADER = "<!-- generated by docspine render · do not edit -->"
# Controlling files from docspine explain UNKNOWN and contradictions; they are not content.
NOT_CONTENT = {"README.md", "STATUS.md"}


def texts(project: Project) -> Dict[str, str]:
    return TEXTS.get(project.language, TEXTS["en"])


# --- small helpers -------------------------------------------------------------------

def epic_status(stories: List[Artifact]) -> str:
    """verified if all stories are verified, open if none has started, else in-progress.

    Stories that are superseded or retired do not count.
    """
    active = {s.get("status") for s in stories if s.get("status") not in ("superseded", "retired")}
    if active == {"verified"}:
        return "verified"
    if active <= {"open"}:
        return "open"
    return "in-progress"


def _stories_of(project: Project, epic_id: str) -> List[Artifact]:
    return [s for s in project.of_kind("story") if s.get("epic") == epic_id]


def _sorted(artifacts: List[Artifact]) -> List[Artifact]:
    return sorted(artifacts, key=lambda a: (a.id or a.path.name))


def _counts(t: Dict[str, str], items: List[Artifact], order, prefix: str) -> str:
    parts = []
    for key in order:
        n = sum(1 for a in items if a.get("status") == key)
        if n:
            parts.append(f"{t[prefix + key]} {n}")
    return " · ".join(parts) if parts else t["none"]


def _link(from_path: Path, to: Artifact, label: Optional[str] = None) -> str:
    rel = Path(_relpath(to.path, from_path.parent))
    return f"[{label or to.id}]({rel.as_posix()})"


def _relpath(target: Path, start: Path) -> str:
    return os.path.relpath(target, start)


# --- region contents -----------------------------------------------------------------

def status_region(project: Project) -> str:
    t = texts(project)
    stories = project.of_kind("story")
    lines = [f"**{len(stories)} {t['stories']}:** {_counts(t, stories, STORY_ORDER, 'story.')}", ""]
    for epic in _sorted(project.of_kind("epic")):
        own = _stories_of(project, epic.id)
        lines += [f"## [{epic.id}](epics/{epic.path.name}) — {epic.get('title')}", "",
                  f"{t['status']}: {t['story.' + epic_status(own)]}", "",
                  f"| Story | {t['title']} | {t['status']} |", "|---|---|---|"]
        lines += [f"| [{s.id}](stories/{s.path.name}) | {s.get('title')} | "
                  f"{t.get('story.' + str(s.get('status')), s.get('status'))} |" for s in own]
        lines.append("")
    return "\n".join(lines).rstrip("\n")


def stories_region(project: Project, epic: Artifact) -> str:
    return "\n".join(f"- [{s.id}](../stories/{s.path.name}) — {s.get('title')}"
                     for s in _stories_of(project, epic.id))


def requirements_region(project: Project, story: Artifact) -> str:
    t = texts(project)
    reqs = project.by_id("requirement")
    rows = [f"| REQ | {t['obligation']} | Statement | {t['status']} |", "|---|---|---|---|"]
    for ref in story.list("requirements"):
        r = reqs.get(ref)
        if r is None:
            continue
        rows.append(f"| {_link(story.path, r)} | {t.get('obligation.' + str(r.get('obligation')), r.get('obligation'))} "
                    f"| {r.get('statement')} | {t.get('req.' + str(r.get('status')), r.get('status'))} |")
    return "\n".join(rows) if len(rows) > 2 else f"_{t['none']}_"


def context_region(project: Project, req: Artifact) -> str:
    t = texts(project)
    epics = project.by_id("epic")
    parts = []
    for s in _sorted([s for s in project.of_kind("story") if req.id in s.list("requirements")]):
        part = f"Story {_link(req.path, s)} — {s.get('title')}"
        epic = epics.get(str(s.get("epic")))
        if epic is not None:
            part += f" · Epic {_link(req.path, epic)} — {epic.get('title')}"
        parts.append(part)
    adrs = [a for a in _sorted(project.of_kind("adr")) if req.id in a.list("requires")]
    if adrs:
        parts.append(f"{t['required_by']}: " + ", ".join(_link(req.path, a) for a in adrs))
    return f"**{t['context']}:** " + ("; ".join(parts) if parts else t["none"])


def _under(path: str, roots: List[str]) -> bool:
    path = path.strip("/")
    for root in roots:
        root = root.strip("/")
        if path == root or path.startswith(root + "/"):
            return True
    return False


def realized_region(project: Project, block: Artifact) -> str:
    t = texts(project)
    roots = block.list("path")
    reqs = [r for r in _sorted(project.of_kind("requirement"))
            if any(_under(e, roots) for e in r.list("evidence"))]
    if not reqs:
        return f"_{t['none']}_"
    return "\n".join(f"- {_link(block.path, r)} {r.get('statement')}" for r in reqs)


def scenarios_region(project: Project, story: Artifact) -> str:
    scenarios = [s for s in project.of_kind("scenario") if story.id in s.list("stories")]
    return "\n".join(f"- {_link(story.path, s, s.get('title'))}" for s in sorted(scenarios, key=lambda s: s.path.name))


# --- generated views -----------------------------------------------------------------

def _content_files(project: Project) -> List[Path]:
    return [p for p in sorted(project.docs.rglob("*.md"))
            if p.name not in NOT_CONTENT or p.parent != project.docs]


def _chapter_exists(project: Project, name: str, created=()) -> bool:
    file = project.docs / f"{name}.md"
    return (project.docs / name).is_dir() or file.is_file() or file in created


def _partial_chapters(project: Project) -> List[str]:
    from . import frontmatter
    out = []
    for name in CHAPTERS:
        for path in (project.docs / f"{name}.md",):
            if path.is_file():
                try:
                    fm, _ = frontmatter.parse(path.read_text(encoding="utf-8"))
                except frontmatter.FrontMatterError:
                    continue
                if fm and str(fm.get("arc42_status", "")).upper() == "PARTIAL":
                    out.append(name)
    return out


_ITEM = r"^[ \t]*(?:(?:[-*+>]|\d+\.)[ \t]+)*"
OPEN_QUESTION = re.compile(_ITEM + r"UNKNOWN\b")
CONTRADICTION = re.compile(r"\(contradiction\)")
_NEW_ITEM = re.compile(r"^[ \t]*(?:[-*+]|\d+\.)[ \t]")


def _marked_lines(project: Project, marker: re.Pattern) -> List[str]:
    """Lines matching `marker`, joined with their indented continuation lines."""
    out = []
    for path in _content_files(project):
        if path.name == "README.md" and path.parent == project.docs:
            continue
        lines = strip_code(path.read_text(encoding="utf-8")).splitlines()
        for i, line in enumerate(lines):
            if not marker.search(line):
                continue
            parts = [re.sub(_ITEM, "", line).strip()]
            for follow in lines[i + 1:]:
                # continuation: indented, not blank, not a new list item
                if not follow.strip() or not follow[:1].isspace() or _NEW_ITEM.match(follow):
                    break
                parts.append(follow.strip())
            rel = path.relative_to(project.docs).as_posix()
            out.append(f"- [{rel}]({rel}): {' '.join(parts)}")
    return out


def status_view(project: Project, created=()) -> str:
    """`created`: files this render run creates, so that they count as existing."""
    t = texts(project)
    missing = [n for n in CHAPTERS if not _chapter_exists(project, n, created)]
    partial = _partial_chapters(project)
    contradictions = _marked_lines(project, CONTRADICTION)
    unknown = _marked_lines(project, OPEN_QUESTION)

    def section(title: str, items: List[str]) -> List[str]:
        return [f"## {title}", ""] + (items or [f"_{t['none']}_"]) + [""]

    lines = [GENERATED_HEADER, "", f"# {t['status_title']}", "",
             f"| | {t['count']} |", "|---|---|",
             f"| {t['stories']} | {_counts(t, project.of_kind('story'), STORY_ORDER, 'story.')} |",
             f"| Requirements | {_counts(t, project.of_kind('requirement'), REQ_ORDER, 'req.')} |",
             f"| {t['decisions']} | {_counts(t, project.of_kind('adr'), ADR_ORDER, 'adr.')} |", ""]
    lines += section(t["missing_chapters"], [f"- {n}" for n in missing])
    lines += section(t["partial_chapters"], [f"- {n}" for n in partial])
    lines += section(t["contradictions"], contradictions)
    lines += section(t["open_questions"], unknown)
    return "\n".join(lines).rstrip("\n") + "\n"


def quality_view(project: Project) -> Optional[str]:
    t = texts(project)
    reqs = [r for r in _sorted(project.of_kind("requirement")) if r.get("category") == "quality"]
    if not reqs:
        return None
    lines = [GENERATED_HEADER, "", f"# {t['quality_title']}", "",
             f"| REQ | Statement | {t['status']} | {t['verification']} |", "|---|---|---|---|"]
    for r in reqs:
        verification = " ".join(str(r.get("verification", "")).split()) or "—"
        lines.append(f"| [{r.id}](01-goals/requirements/{r.path.name}) | {r.get('statement')} | "
                     f"{t.get('req.' + str(r.get('status')), r.get('status'))} | {verification} |")
    return "\n".join(lines) + "\n"


# --- planning and writing ------------------------------------------------------------

def _region(kind: str) -> re.Pattern:
    return re.compile(r"<!-- generated:" + kind + r" -->\n.*?<!-- /generated -->", re.S)


def _with_region(old: Optional[str], kind: str, content: str, heading: str, add: bool) -> Optional[str]:
    """Return the text with the region replaced or appended; None if nothing is to be added."""
    block = f"<!-- generated:{kind} -->\n{content}\n<!-- /generated -->"
    if old is None:
        return f"{heading}\n\n{block}\n" if heading else f"{block}\n"
    if _region(kind).search(old):
        return _region(kind).sub(lambda m: block, old, count=1)
    if not add:
        return None
    prefix = f"\n\n{heading}\n\n" if heading else "\n\n"
    return old.rstrip("\n") + prefix + block + "\n"


def plan(project: Project) -> Dict[Path, str]:
    """Path -> complete new text, for every file render manages."""
    t = texts(project)
    current: Dict[Path, Optional[str]] = {}

    def text_of(path: Path) -> Optional[str]:
        if path not in current:
            current[path] = path.read_text(encoding="utf-8") if path.exists() else None
        return current[path]

    def apply(path: Path, kind: str, content: str, heading: str, add: bool = True):
        new = _with_region(text_of(path), kind, content, heading, add)
        if new is not None:
            current[path] = new

    goals = project.docs / "01-goals"
    if goals.is_dir():
        apply(goals / "README.md", "status", status_region(project), f"# {t['goals']}")
    for epic in project.of_kind("epic"):
        apply(epic.path, "stories", stories_region(project, epic), f"## {t['stories']}")
    for story in project.of_kind("story"):
        apply(story.path, "requirements", requirements_region(project, story), "## Requirements",
              add=bool(story.list("requirements")))
        scenarios = scenarios_region(project, story)
        apply(story.path, "scenarios", scenarios or f"_{t['none']}_", f"## {t['scenarios']}", add=bool(scenarios))
    for req in project.of_kind("requirement"):
        apply(req.path, "context", context_region(project, req), "")
    for block in project.of_kind("block"):
        apply(block.path, "realized", realized_region(project, block), f"## {t['realized']}")

    result = {p: text for p, text in current.items() if text is not None}
    quality = quality_view(project)
    if quality is not None:
        result[project.docs / "10-quality.md"] = quality
    result[project.docs / "STATUS.md"] = status_view(project, created=set(result))
    return result


def stale(project: Project) -> List[Path]:
    """Files whose content differs from what render would write."""
    out = []
    for path, text in plan(project).items():
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            out.append(path)
    return sorted(out)


def run(project: Project) -> List[str]:
    """Write all generated regions and views. Returns the files that changed."""
    changed = []
    for path, text in sorted(plan(project).items()):
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            changed.append(project.rel(path))
    return changed
