"""`docspine render`: generated regions and views (STANDARD.md sections 4 and 11).

`plan()` computes the complete new text of every file render manages. `run()` writes the
files that differ; `check` uses the same plan to report regions that are out of date.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, List, Optional

from .project import Artifact, Project
from .text import TEXTS, blank, blank_code

STORY_ORDER = ("open", "in-progress", "verified", "superseded", "retired")
REQ_ORDER = ("proposed", "planned", "implemented", "rejected", "superseded")
ADR_ORDER = ("proposed", "accepted", "rejected", "superseded")
RISK_GROUPS = ("R", "SEC", "TD")
CHAPTERS = ("01-goals", "02-constraints", "03-context", "04-strategy", "05-building-blocks",
            "06-runtime", "07-deployment", "08-concepts", "09-decisions", "10-quality",
            "11-risks", "12-glossary")
GENERATED_HEADER = "<!-- generated by docspine render · do not edit -->"
# Not content: the README from docspine explains UNKNOWN and contradictions; STATUS.md is the
# generated view of versions before 0.3 and is removed by docspine-update.
NOT_CONTENT = {"README.md", "STATUS.md"}


def texts(project: Project) -> Dict[str, str]:
    return TEXTS.get(project.language, TEXTS["en"])


# --- small helpers -------------------------------------------------------------------

def epic_status(stories: List[Artifact]) -> str:
    """verified if all stories are verified, open if none has started, else in-progress.

    Stories that are superseded or retired do not count.
    """
    active = {s.get("status") for s in stories if s.get("status") not in ("superseded", "retired")}
    if active == {"verified"}:
        return "verified"
    if active <= {"open"}:
        return "open"
    return "in-progress"


def _stories_of(project: Project, epic_id: str) -> List[Artifact]:
    return [s for s in project.of_kind("story") if s.get("epic") == epic_id]


def _sorted(artifacts: List[Artifact]) -> List[Artifact]:
    return sorted(artifacts, key=lambda a: (a.id or a.path.name))


def _counts(t: Dict[str, str], items: List[Artifact], order, prefix: str) -> str:
    parts = []
    for key in order:
        n = sum(1 for a in items if a.get("status") == key)
        if n:
            parts.append(f"{t[prefix + key]} {n}")
    return " · ".join(parts) if parts else t["none"]


def _link(from_path: Path, to: Artifact, label: Optional[str] = None) -> str:
    rel = Path(_relpath(to.path, from_path.parent))
    return f"[{label or to.id}]({rel.as_posix()})"


def _relpath(target: Path, start: Path) -> str:
    return os.path.relpath(target, start)


# --- region contents -----------------------------------------------------------------

def status_region(project: Project, created=()) -> str:
    """The entry into the documentation: counts, epics and stories, then what is open.

    `created`: files this render run creates, so that they count as existing chapters.
    """
    t = texts(project)
    goals = project.docs / "01-goals"
    stories = project.of_kind("story")
    decisions = (f"[{t['decisions']}](../09-decisions/)" if (project.docs / "09-decisions").is_dir()
                 else t["decisions"])
    lines = [f"| | {t['count']} |", "|---|---|",
             f"| {t['stories']} | {_counts(t, stories, STORY_ORDER, 'story.')} |",
             f"| Requirements | {_counts(t, project.of_kind('requirement'), REQ_ORDER, 'req.')} |",
             f"| {decisions} | {_counts(t, project.of_kind('adr'), ADR_ORDER, 'adr.')} |", ""]
    for epic in _sorted(project.of_kind("epic")):
        own = _stories_of(project, epic.id)
        lines += [f"## [{epic.id}](epics/{epic.path.name}) — {epic.get('title')}", "",
                  f"{t['status']}: {t['story.' + epic_status(own)]}", "",
                  f"| Story | {t['title']} | {t['status']} |", "|---|---|---|"]
        lines += [f"| [{s.id}](stories/{s.path.name}) | {s.get('title')} | "
                  f"{t.get('story.' + str(s.get('status')), s.get('status'))} |" for s in own]
        lines.append("")

    def section(title: str, items: List[str]) -> None:
        lines.extend([f"## {title}", ""] + (items or [f"_{t['none']}_"]) + [""])

    section(t["open_questions"], _marked_lines(project, OPEN_QUESTION, goals))
    section(t["open_decisions"], [f"- {_link(goals / 'README.md', a)} — {a.get('title')}"
                                  for a in _sorted(project.of_kind("adr")) if a.get("status") == "proposed"])
    section(t["contradictions"], _marked_lines(project, CONTRADICTION, goals))
    section(t["missing_chapters"], [f"- {n}" for n in CHAPTERS if not _chapter_exists(project, n, created)])
    section(t["partial_chapters"], [f"- {n}" for n in _partial_chapters(project)])
    return "\n".join(lines).rstrip("\n")


def stories_region(project: Project, epic: Artifact) -> str:
    return "\n".join(f"- [{s.id}](../stories/{s.path.name}) — {s.get('title')}"
                     for s in _stories_of(project, epic.id))


def requirements_region(project: Project, story: Artifact) -> str:
    t = texts(project)
    reqs = project.by_id("requirement")
    rows = [f"| REQ | {t['obligation']} | Statement | {t['status']} |", "|---|---|---|---|"]
    for ref in story.list("requirements"):
        r = reqs.get(ref)
        if r is None:
            continue
        rows.append(f"| {_link(story.path, r)} | {t.get('obligation.' + str(r.get('obligation')), r.get('obligation'))} "
                    f"| {r.get('statement')} | {t.get('req.' + str(r.get('status')), r.get('status'))} |")
    return "\n".join(rows) if len(rows) > 2 else f"_{t['none']}_"


def context_region(project: Project, req: Artifact) -> str:
    t = texts(project)
    epics = project.by_id("epic")
    parts = []
    for s in _sorted([s for s in project.of_kind("story") if req.id in s.list("requirements")]):
        part = f"Story {_link(req.path, s)} — {s.get('title')}"
        epic = epics.get(str(s.get("epic")))
        if epic is not None:
            part += f" · Epic {_link(req.path, epic)} — {epic.get('title')}"
        parts.append(part)
    adrs = project.by_id("adr")
    decisions = [adrs[ref] for ref in req.list("decisions") if ref in adrs]
    if decisions:
        parts.append(f"{t['decided_by']}: " + ", ".join(_link(req.path, a) for a in decisions))
    return f"**{t['context']}:** " + ("; ".join(parts) if parts else t["none"])


def adr_requirements_region(project: Project, adr: Artifact) -> str:
    t = texts(project)
    reqs = [r for r in _sorted(project.of_kind("requirement")) if adr.id in r.list("decisions")]
    rows = [f"| REQ | Statement | {t['status']} |", "|---|---|---|"]
    rows += [f"| {_link(adr.path, r)} | {r.get('statement')} | {t.get('req.' + str(r.get('status')), r.get('status'))} |"
             for r in reqs]
    return "\n".join(rows) if reqs else f"_{t['none']}_"


def _under(path: str, roots: List[str]) -> bool:
    path = path.strip("/")
    for root in roots:
        root = root.strip("/")
        if path == root or path.startswith(root + "/"):
            return True
    return False


def realized_region(project: Project, block: Artifact) -> str:
    t = texts(project)
    roots = block.list("path")
    # the block shows what its code does today; superseded and rejected ones are history
    reqs = [r for r in _sorted(project.of_kind("requirement"))
            if r.get("status") not in ("superseded", "rejected")
            and any(_under(e, roots) for e in r.list("evidence"))]
    if not reqs:
        return f"_{t['none']}_"
    return "\n".join(f"- {_link(block.path, r)} {r.get('statement')}" for r in reqs)


def scenarios_region(project: Project, story: Artifact) -> str:
    scenarios = [s for s in project.of_kind("scenario") if story.id in s.list("stories")]
    return "\n".join(f"- {_link(story.path, s, s.get('title'))}" for s in sorted(scenarios, key=lambda s: s.path.name))


def _addressing(project: Project, risk: Artifact) -> List[Artifact]:
    return _sorted([s for s in project.of_kind("story") if risk.id in s.list("addresses")])


def risk_stories_region(project: Project, risk: Artifact) -> str:
    t = texts(project)
    rows = [f"| Story | {t['title']} | {t['status']} |", "|---|---|---|"]
    rows += [f"| {_link(risk.path, s)} | {s.get('title')} | "
             f"{t.get('story.' + str(s.get('status')), s.get('status'))} |" for s in _addressing(project, risk)]
    return "\n".join(rows) if len(rows) > 2 else f"_{t['none']}_"


def risks_region(project: Project, readme: Path) -> str:
    """Chapter 11 as a whole: every risk, grouped by its prefix."""
    t = texts(project)
    lines = []
    for group in RISK_GROUPS:
        risks = [r for r in _sorted(project.of_kind("risk")) if (r.id or "").startswith(group + "-")]
        if not risks:
            continue
        lines += [f"## {t['group.' + group]}", "",
                  f"| ID | {t['title']} | {t['status']} | {t['severity']} | Stories |", "|---|---|---|---|---|"]
        for r in risks:
            severity = t.get("severity." + str(r.get("severity")), r.get("severity")) or "—"
            stories = ", ".join(f"{_link(readme, s)} {t.get('story.' + str(s.get('status')), s.get('status'))}"
                                for s in _addressing(project, r)) or "—"
            lines.append(f"| {_link(readme, r)} | {r.get('title')} | "
                         f"{t.get('risk.' + str(r.get('status')), r.get('status'))} | {severity} | {stories} |")
        lines.append("")
    return "\n".join(lines).rstrip("\n")


# --- generated views -----------------------------------------------------------------

def _content_files(project: Project) -> List[Path]:
    return [p for p in sorted(project.docs.rglob("*.md"))
            if p.name not in NOT_CONTENT or p.parent != project.docs]


def _chapter_exists(project: Project, name: str, created=()) -> bool:
    file = project.docs / f"{name}.md"
    return (project.docs / name).is_dir() or file.is_file() or file in created


def _partial_chapters(project: Project) -> List[str]:
    from . import frontmatter
    out = []
    for name in CHAPTERS:
        for path in (project.docs / f"{name}.md",):
            if path.is_file():
                try:
                    fm, _ = frontmatter.parse(path.read_text(encoding="utf-8"))
                except frontmatter.FrontMatterError:
                    continue
                if fm and str(fm.get("arc42_status", "")).upper() == "PARTIAL":
                    out.append(name)
    return out


_ITEM = r"^[ \t]*(?:(?:[-*+>]|\d+\.)[ \t]+)*"
# an acceptance criterion carries its ID before the open question (ADR-0031)
OPEN_QUESTION = re.compile(_ITEM + r"(?:AC-\d+:[ \t]*)?UNKNOWN\b")
CONTRADICTION = re.compile(r"\(contradiction\)")
_NEW_ITEM = re.compile(r"^[ \t]*(?:[-*+]|\d+\.)[ \t]")


_GENERATED = re.compile(r"<!-- generated:[^>]*-->.*?<!-- /generated -->", re.S)


def _marked_lines(project: Project, marker: re.Pattern, base: Path) -> List[str]:
    """Lines matching `marker`, joined with their indented continuation lines.

    Generated regions are skipped: they list these lines themselves.
    """
    out = []
    for path in _content_files(project):
        if path.name == "README.md" and path.parent == project.docs:
            continue
        text = path.read_text(encoding="utf-8")
        # markers are searched outside code and generated regions, but the original line is
        # listed, so that code spans in a question stay visible
        searched = blank(blank_code(text), _GENERATED).splitlines()
        lines = text.splitlines()
        for i, line in enumerate(searched):
            if not marker.search(line):
                continue
            parts = [re.sub(_ITEM, "", lines[i]).strip()]
            for j in range(i + 1, len(lines)):
                follow = lines[j]
                # continuation: indented, not blank, not a new list item, not code
                if not searched[j].strip() or not follow[:1].isspace() or _NEW_ITEM.match(follow):
                    break
                parts.append(follow.strip())
            label = path.relative_to(project.docs).as_posix()
            out.append(f"- [{label}]({_relpath(path, base)}): {' '.join(parts)}")
    return out


def quality_view(project: Project) -> Optional[str]:
    t = texts(project)
    reqs = [r for r in _sorted(project.of_kind("requirement")) if r.get("category") == "quality"]
    if not reqs:
        return None
    lines = [GENERATED_HEADER, "", f"# {t['quality_title']}", "",
             f"| REQ | Statement | {t['status']} | {t['verification']} |", "|---|---|---|---|"]
    for r in reqs:
        verification = " ".join(str(r.get("verification", "")).split()) or "—"
        lines.append(f"| [{r.id}](01-goals/requirements/{r.path.name}) | {r.get('statement')} | "
                     f"{t.get('req.' + str(r.get('status')), r.get('status'))} | {verification} |")
    return "\n".join(lines) + "\n"


# --- planning and writing ------------------------------------------------------------

def _region(kind: str) -> re.Pattern:
    return re.compile(r"<!-- generated:" + kind + r" -->\n.*?<!-- /generated -->", re.S)


def _with_region(old: Optional[str], kind: str, content: str, heading: str, add: bool) -> Optional[str]:
    """Return the text with the region replaced or appended; None if nothing is to be added."""
    block = f"<!-- generated:{kind} -->\n{content}\n<!-- /generated -->"
    if old is None:
        return f"{heading}\n\n{block}\n" if heading else f"{block}\n"
    if _region(kind).search(old):
        return _region(kind).sub(lambda m: block, old, count=1)
    if not add:
        return None
    prefix = f"\n\n{heading}\n\n" if heading else "\n\n"
    return old.rstrip("\n") + prefix + block + "\n"


def plan(project: Project) -> Dict[Path, str]:
    """Path -> complete new text, for every file render manages."""
    t = texts(project)
    current: Dict[Path, Optional[str]] = {}

    def text_of(path: Path) -> Optional[str]:
        if path not in current:
            current[path] = path.read_text(encoding="utf-8") if path.exists() else None
        return current[path]

    def apply(path: Path, kind: str, content: str, heading: str, add: bool = True):
        new = _with_region(text_of(path), kind, content, heading, add)
        if new is not None:
            current[path] = new

    quality = quality_view(project)
    created = {project.docs / "10-quality.md"} if quality is not None else set()
    goals = project.docs / "01-goals"
    if goals.is_dir():
        apply(goals / "README.md", "status", status_region(project, created), f"# {t['goals']}")
    for epic in project.of_kind("epic"):
        apply(epic.path, "stories", stories_region(project, epic), f"## {t['stories']}")
    for story in project.of_kind("story"):
        apply(story.path, "requirements", requirements_region(project, story), "## Requirements",
              add=bool(story.list("requirements")))
        scenarios = scenarios_region(project, story)
        apply(story.path, "scenarios", scenarios or f"_{t['none']}_", f"## {t['scenarios']}", add=bool(scenarios))
    for req in project.of_kind("requirement"):
        apply(req.path, "context", context_region(project, req), "")
    for adr in project.of_kind("adr"):
        reqs = adr_requirements_region(project, adr)
        apply(adr.path, "requirements", reqs, "## Requirements",
              add=any(adr.id in r.list("decisions") for r in project.of_kind("requirement")))
    for block in project.of_kind("block"):
        apply(block.path, "realized", realized_region(project, block), f"## {t['realized']}")
    for risk in project.of_kind("risk"):
        apply(risk.path, "stories", risk_stories_region(project, risk), "## Stories")
    if project.of_kind("risk"):
        readme = project.docs / "11-risks" / "README.md"
        # a hand-written README keeps its own heading; a new one gets the chapter title
        heading = f"# {t['risks_title']}" if text_of(readme) is None else ""
        apply(readme, "risks", risks_region(project, readme), heading)

    result = {p: text for p, text in current.items() if text is not None}
    if quality is not None:
        result[project.docs / "10-quality.md"] = quality
    return result


def stale(project: Project) -> List[Path]:
    """Files whose content differs from what render would write."""
    out = []
    for path, text in plan(project).items():
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            out.append(path)
    return sorted(out)


def run(project: Project) -> List[str]:
    """Write all generated regions and views. Returns the files that changed."""
    changed = []
    for path, text in sorted(plan(project).items()):
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            changed.append(project.rel(path))
    return changed
